services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: knights
    ports:
      - "27017:27017"
    volumes:
      - dataMongo:/data/db
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
  knight.api:
    image: ${DOCKER_REGISTRY-}knightapi
    depends_on:
      - mongo
    build:
      context: ./api
      dockerfile: Knight.Api/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - "Data:KnightConnection=User ID=postgres;Password=!123@Mudar;Host=postgres;Port=5432;Database=knight;Pooling=true;"
      - "MONGODB_URI=mongodb://admin:admin@mongo:27017"
      - "MONGODB_DATABASE=knights"
  knight.front:
    image: ${DOCKER_REGISTRY-}knightfront
    depends_on:
      - knight.api
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 8090:8080
volumes:
  data: {}
  dataMongo: {}
